name: Node.js CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.12.1
      with:
        mongodb-version: 7

    - name: unit test
      run: npm run test:unit

    - name: Cypress.io
      uses: cypress-io/github-action@v7.1.9
      with:
        start: npm run start:test